live_config_reload = true

[colors.bright]
black = "0x808080"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xFFFFFF"
yellow = "0xfeff00"

[colors.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xd0d0d0"
yellow = "0xfeff00"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "Ubuntu Mono"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
opacity = 1
